name: Update version.txt

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main  # <--- обязательно checkout не тега, а main

      - name: Extract version from tag
        run: echo "${GITHUB_REF#refs/tags/}" > version.txt

      - name: Commit and push version.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Update version.txt to ${GITHUB_REF#refs/tags/}" || echo "No changes to commit"
          git push origin main
