name: update-version

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # нужен полный fetch, чтобы видеть все ветки

      - name: Update version.txt
        run: echo "${GITHUB_REF#refs/tags/}" > version.txt

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout main  # <-- переключаемся на основную ветку (ИЗМЕНИТЕ если у вас master)
          git pull origin main
          git add version.txt
          git commit -m "Update version.txt to ${GITHUB_REF#refs/tags/}" || echo "No changes"
          git push origin main
