name: update-version

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # отключаем авто-учётку, чтобы задать вручную

      - name: Update version.txt
        run: |
          echo "${GITHUB_REF#refs/tags/}" > version.txt

      - name: Commit and push version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add version.txt
          git commit -m "Update version.txt to ${GITHUB_REF#refs/tags/}"
          git push origin HEAD:main
